// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/huangyul/gin-vue-template/internal/ioc"
)

// Injectors from wire.go:

func InitServer() *gin.Engine {
	v := ioc.InitWebMiddleware()
	engine := ioc.InitServer(v)
	return engine
}
